# Generated by Django 3.1.3 on 2020-11-09 16:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BdpGeneralFiltrada',
            fields=[
                ('index', models.BigIntegerField(blank=True, db_column='index', null=True)),
                ('cod_perfil', models.TextField(db_column='COD_PERFIL', primary_key=True, serialize=False, unique=True)),
                ('simbolo_ucs', models.TextField(blank=True, db_column='SIMBOLO_UCS', null=True)),
                ('tipo_ucs', models.TextField(blank=True, db_column='TIPO_UCS', null=True)),
                ('departamento', models.TextField(blank=True, db_column='DEPARTAMENTO', null=True)),
                ('clase_pendiente', models.TextField(blank=True, db_column='CLASE_PENDIENTE', null=True)),
                ('porc_pendiente', models.TextField(blank=True, db_column='PORC_PENDIENTE', null=True)),
                ('memoria', models.TextField(blank=True, db_column='MEMORIA', null=True)),
                ('drenaje_interno', models.TextField(blank=True, db_column='DRENAJE_INTERNO', null=True)),
                ('drenaje_externo', models.TextField(blank=True, db_column='DRENAJE_EXTERNO', null=True)),
                ('drenaje_natural', models.TextField(blank=True, db_column='DRENAJE_NATURAL', null=True)),
                ('profundidad_efectiva', models.TextField(blank=True, db_column='PROFUNDIDAD_EFECTIVA', null=True)),
                ('longitud_pendiente', models.TextField(blank=True, db_column='LONGITUD_PENDIENTE', null=True)),
                ('forma_pendiente', models.TextField(blank=True, db_column='FORMA_PENDIENTE', null=True)),
                ('regimen_humedad', models.TextField(blank=True, db_column='REGIMEN_HUMEDAD', null=True)),
                ('clase_erosion', models.TextField(blank=True, db_column='CLASE_EROSION', null=True)),
                ('tipo_erosion', models.TextField(blank=True, db_column='TIPO_EROSION', null=True)),
                ('grado_erosion', models.TextField(blank=True, db_column='GRADO_EROSION', null=True)),
                ('tipo_pedregosidad', models.TextField(blank=True, db_column='TIPO_PEDREGOSIDAD', null=True)),
                ('porc_pedregosidad_superficial_cubierta', models.TextField(blank=True, db_column='PORC_PEDREGOSIDAD_SUPERFICIAL_CUBIERTA', null=True)),
                ('clase_pedregosidad', models.TextField(blank=True, db_column='CLASE_PEDREGOSIDAD', null=True)),
                ('fase_inundacion_encharcamiento', models.TextField(blank=True, db_column='FASE_INUNDACION_ENCHARCAMIENTO', null=True)),
                ('frecuencia_inundacion', models.TextField(blank=True, db_column='FRECUENCIA_INUNDACION', null=True)),
                ('duracion_inundacion', models.TextField(blank=True, db_column='DURACION_INUNDACION', null=True)),
                ('frecuencia_encharcamiento', models.TextField(blank=True, db_column='FRECUENCIA_ENCHARCAMIENTO', null=True)),
                ('duracion_encharcamiento', models.TextField(blank=True, db_column='DURACION_ENCHARCAMIENTO', null=True)),
                ('caracteristicas_diagnosticas', models.TextField(blank=True, db_column='CARACTERISTICAS_DIAGNOSTICAS', null=True)),
                ('clasificacion_taxonomica', models.TextField(blank=True, db_column='CLASIFICACION_TAXONOMICA', null=True)),
                ('familia_textural', models.TextField(blank=True, db_column='FAMILIA_TEXTURAL', null=True)),
                ('epipedon', models.TextField(blank=True, db_column='EPIPEDON', null=True)),
                ('endopedon_1', models.TextField(blank=True, db_column='ENDOPEDON_1', null=True)),
                ('endopedon_2', models.TextField(blank=True, db_column='ENDOPEDON_2', null=True)),
                ('fase_desp_fam_text', models.TextField(blank=True, db_column='FASE_desp_fam_text', null=True)),
                ('fecha_ajustada', models.DateTimeField(db_column='Fecha_Ajustada')),
            ],
            options={
                'verbose_name': 'BDP General',
                'verbose_name_plural': '1. BDP General',
                'db_table': 'bdp_general_filtrada',
            },
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('index', models.AutoField(db_column='index', primary_key=True, serialize=False)),
                ('latitud', models.FloatField(db_column='LATITUD')),
                ('longitud', models.FloatField(db_column='LONGITUD')),
                ('cod_perfil', models.OneToOneField(db_column='COD_PERFIL', on_delete=django.db.models.deletion.CASCADE, to='persistance.bdpgeneralfiltrada')),
            ],
            options={
                'verbose_name': 'Coordenadas',
                'verbose_name_plural': '4. Coordenadas',
                'db_table': 'coordenadas',
            },
        ),
        migrations.CreateModel(
            name='BdpDetalladaFiltrada',
            fields=[
                ('index', models.BigIntegerField(blank=True, db_column='index', null=True)),
                ('horizontes', models.TextField(db_column='HORIZONTES', primary_key=True, serialize=False, unique=True)),
                ('profundidad_efectiva', models.TextField(blank=True, db_column='PROFUNDIDAD_EFECTIVA', null=True)),
                ('color_matriz_seco1', models.TextField(blank=True, db_column='COLOR_MATRIZ_SECO1', null=True)),
                ('color_matriz_seco2', models.TextField(blank=True, db_column='COLOR_MATRIZ_SECO2', null=True)),
                ('color_matriz_humedo1', models.TextField(blank=True, db_column='COLOR_MATRIZ_HUMEDO1', null=True)),
                ('color_matriz_humedo2', models.TextField(blank=True, db_column='COLOR_MATRIZ_HUMEDO2', null=True)),
                ('consistencia_seco', models.TextField(blank=True, db_column='CONSISTENCIA_SECO', null=True)),
                ('consistencia_humedo', models.TextField(blank=True, db_column='CONSISTENCIA_HÚMEDO', null=True)),
                ('consist_mojado_pegj', models.TextField(blank=True, db_column='CONSIST_MOJADO_PEGJ', null=True)),
                ('consist_mojado_pl', models.TextField(blank=True, db_column='CONSIST_MOJADO_PL', null=True)),
                ('clase_erosion', models.TextField(blank=True, db_column='CLASE_EROSION', null=True)),
                ('tipo_erosion', models.TextField(blank=True, db_column='TIPO_EROSION', null=True)),
                ('grado_erosion', models.TextField(blank=True, db_column='GRADO_EROSION', null=True)),
                ('evidencias_erosion', models.TextField(blank=True, db_column='EVIDENCIAS_EROSION', null=True)),
                ('municipio', models.TextField(blank=True, db_column='MUNICIPIO', null=True)),
                ('regimen_temperatura', models.TextField(blank=True, db_column='REGIMEN_TEMPERATURA', null=True)),
                ('regimen_humedad', models.TextField(blank=True, db_column='REGIMEN_HUMEDAD', null=True)),
                ('descripcion_horizonte', models.TextField(blank=True, db_column='DESCRIPCIÓN_HORIZONTE', null=True)),
                ('horizonte_class', models.TextField(blank=True, db_column='Horizonte_class', null=True)),
                ('izquierda_clas_tax', models.TextField(blank=True, db_column='IZQUIERDA_CLAS_TAX', null=True)),
                ('derecha_clasificacion_tax', models.TextField(blank=True, db_column='DERECHA_CLASIFICACION_TAX', null=True)),
                ('metodo_ph', models.TextField(blank=True, db_column='METODO_ph', null=True)),
                ('edafologo', models.TextField(blank=True, db_column='EDAFOLOGO', null=True)),
                ('resultado_ph', models.FloatField(blank=True, db_column='RESULTADO_ph', null=True)),
                ('espesor', models.FloatField(blank=True, db_column='ESPESOR', null=True)),
                ('cod_perfil', models.ForeignKey(db_column='COD_PERFIL', on_delete=django.db.models.deletion.CASCADE, to='persistance.bdpgeneralfiltrada')),
            ],
            options={
                'verbose_name': 'BDP Detallada',
                'verbose_name_plural': '2. BDP Detallada',
                'db_table': 'bdp_detallada_filtrada',
            },
        ),
        migrations.CreateModel(
            name='BdlDetalladaFiltrada',
            fields=[
                ('index', models.AutoField(db_column='index', primary_key=True, serialize=False)),
                ('clase_textural', models.TextField(blank=True, db_column='Clase Textural', null=True)),
                ('carbono_organico_co_percentage_field', models.FloatField(blank=True, db_column='CARBONO ORGANICO {CO Percentage}', null=True)),
                ('ph_1_1_field', models.FloatField(blank=True, db_column='pH {1:1}', null=True)),
                ('profundidades', models.FloatField(blank=True, db_column='Profundidades', null=True)),
                ('cica', models.FloatField(blank=True, db_column='CICA', null=True)),
                ('cice', models.FloatField(blank=True, db_column='CICE', null=True)),
                ('cicv', models.FloatField(blank=True, db_column='CICV', null=True)),
                ('number_0_kpa_field', models.FloatField(blank=True, db_column='0{kPa}', null=True)),
                ('field_33_kpa_field', models.FloatField(blank=True, db_column='-33{kPa}', null=True)),
                ('field_100_kpa_field', models.FloatField(blank=True, db_column='-100{kPa}', null=True)),
                ('field_500_kpa_field', models.FloatField(blank=True, db_column='-500{kPa}', null=True)),
                ('field_1500_kpa_field', models.FloatField(blank=True, db_column='-1500{kPa}', null=True)),
                ('real_g_cm3_field', models.FloatField(blank=True, db_column='REAL {g/cm3}', null=True)),
                ('aparente_g_cm3_field', models.FloatField(blank=True, db_column='APARENTE{g/cm3}', null=True)),
                ('fosforo_disponible', models.FloatField(blank=True, db_column='FÓSFORO DISPONIBLE', null=True)),
                ('porosidad_total_percentage_field', models.FloatField(blank=True, db_column='Porosidad Total {Percentage}', null=True)),
                ('cod_perfil', models.ForeignKey(db_column='COD_PERFIL', on_delete=django.db.models.deletion.CASCADE, to='persistance.bdpgeneralfiltrada')),
                ('horizontes', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cod_perfil', chained_model_field='cod_perfil', db_column='HORIZONTES', on_delete=django.db.models.deletion.CASCADE, to='persistance.bdpdetalladafiltrada')),
            ],
            options={
                'verbose_name': 'BDL Detallada',
                'verbose_name_plural': '3. BDL Detallada',
                'db_table': 'bdl_detallada_filtrada',
            },
        ),
    ]
